(EasySetup): provide an option to store certificates in a separate folder from Greengrass Root #971
aws-greengrass/aws-greengrass-nucleus pull request #1305
Opened 2022-09-13 05:53 UTC by ChangxinDong

**Issue #, if available:**

**Description of changes:**

**Why is this change necessary:**

**How was this change tested:**
- [ ] Updated or added new unit tests.
- [ ] Updated or added new integration tests.
- [ ] Updated or added new end-to-end tests.
- [ ] If my code makes a remote network call, it was tested with a proxy.

**Any additional information or context required to review the change:**

**Documentation Checklist:**
 - [ ] Updated the README if applicable.

**Compatibility Checklist:**
- [ ] I confirm that the change is backwards compatible.
- [ ] Any modification or deletion of public interfaces does not impact other plugin components.
- [ ] For external library version updates, I have reviewed its change logs and Nucleus does not consume 
  any deprecated method or type.

Refer to [Compatibility Guidelines](/COMPATIBILITY.md) for more information.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-09-13 05:57 UTC, MikeDombo commented on src/main/java/com/aws/greengrass/easysetup/DeviceProvisioningHelper.java
> +                    tmpFile.mkdirs();
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Confirm that `mkdirs` was successful. Handle any failures that happened. If you fail silently, then you might encounter errors that are harder to debug. See the following diffs on GitHub that make this code change: [diff1](https://github.com/qunarcorp/qmq/commit/12f1d9d6a57a02bc2415cb2af9f4388a77b12c02#diff-6b67be6e17f24fdeddb7c725ac8ec5600d6e63be0bdca0963a83d530e6d55e35L36), [diff2](https://github.com/apache/jmeter/commit/1ec61206779b3f84df18516682b4791bf015178f#diff-cd74304763c097fbc085ac2bc952b46ab3843ac825cacacad89e8064296e955aL330)

Learn more: [File.mkdirs in the Java Platform, Standard Edition 8 API Specification](https://docs.oracle.com/javase/8/docs/api/java/io/File.html#mkdirs--)

2022-09-13 12:04 UTC, MikeDombo commented on src/main/java/com/aws/greengrass/easysetup/DeviceProvisioningHelper.java
> +                    tmpFile.mkdirs();
Use `Utils.createPaths()`. https://github.com/aws-greengrass/aws-greengrass-nucleus/blob/main/src/main/java/com/aws/greengrass/util/Utils.java#L621

2022-09-13 12:08 UTC, MikeDombo requested changes

2022-09-13 12:08 UTC, MikeDombo commented on src/main/java/com/aws/greengrass/easysetup/DeviceProvisioningHelper.java
> +                outStream.println("certPath is not valid,download certificates in the default path");
space is required after `,`

2022-09-13 12:08 UTC, MikeDombo commented on src/main/java/com/aws/greengrass/easysetup/GreengrassSetup.java
> +    private static final String CERT_PATH_ARG_SHORT = "-cp";
Don't have add a short version for this, only have the full name for this option.

2022-09-13 12:08 UTC, MikeDombo commented on src/test/java/com/aws/greengrass/easysetup/DeviceProvisioningHelperTest.java
> +                        "xxxxxx.credentials.iot.us-east-1.amazonaws.com"), TEST_REGION, "roleAliasName", "certPath");
use the default value, which should be `null`

2022-09-13 12:08 UTC, MikeDombo commented on src/integrationtests/java/com/aws/greengrass/integrationtests/e2e/tes/TESTest.java
> +        deviceProvisioningHelper.updateKernelConfigWithIotConfiguration(kernel, thingInfo, AWS_REGION, roleAliasName, "certPath");
use null

2022-09-13 12:08 UTC, MikeDombo commented on src/integrationtests/java/com/aws/greengrass/integrationtests/e2e/mqttclient/MqttTest.java
> +    public static final String CERT_PATH = "certPath";
use null for all of these. 

Also, this should not be `public`.

2022-09-13 12:08 UTC, MikeDombo commented on src/integrationtests/java/com/aws/greengrass/integrationtests/e2e/BaseE2ETestCase.java
> +                TES_ROLE_ALIAS_NAME, "certPath");
use null

2022-09-13 12:10 UTC, MikeDombo commented
@ChangxinDong,

Please review the test failures: https://github.com/aws-greengrass/aws-greengrass-nucleus/actions/runs/3042673695/jobs/4905782418
and address them.

All of your commits must follow conventional commits format: https://www.conventionalcommits.org/en/v1.0.0/.

2022-09-14 23:10 UTC, MikeDombo requested changes

2022-09-14 23:10 UTC, MikeDombo commented on src/main/java/com/aws/greengrass/easysetup/GreengrassSetup.java
> +                case CERT_PATH_ARG:
Add the cert path option into the help text output.

2022-09-14 23:10 UTC, MikeDombo commented on src/main/java/com/aws/greengrass/easysetup/DeviceProvisioningHelper.java
> +            File tmpFile = new File(certPath);
Do not do any of this with File. Simply create the path using the util method when the path is specified by the user.

2022-09-15 13:41 UTC, MikeDombo commented on src/main/java/com/aws/greengrass/easysetup/GreengrassSetup.java
> +            + "then use the default path.\n";
`(Optional) Path where certificates and keys are written when --provision is true. If no path is specified, the root directory is used.`

2022-09-15 13:41 UTC, MikeDombo commented on src/test/java/com/aws/greengrass/easysetup/GreengrassSetupTest.java
> +    @CsvSource({"--cert-path,/a/b", "-cp,/a/b"})
this test must fail now.

You removed `-cp`, so this cannot work.

2022-09-15 20:47 UTC, MikeDombo approved these changes

2022-09-15 21:11 UTC, junfuchen99 commented on src/main/java/com/aws/greengrass/easysetup/DeviceProvisioningHelper.java
>          Path certFilePath = rootDir.resolve("thingCert.crt");
nit: rename `rootDir` to `certPath` and rename `certPath` to maybe `userCertPath`, since it's no longer just root directory

2022-09-15 23:57 UTC, junfuchen99 approved these changes

2022-09-16 03:23 UTC, MikeDombo approved these changes

2022-09-16 13:57 UTC, merged